<a href="https://colab.research.google.com/github/geharpz/algoritmos_optimizacion_miar2023/blob/seminario/src/seminario/Seminario_Algoritmos_Diocles_German_Avendano_Ponce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos:Diocles Germán Avendaño Ponce <br>
Url: https://github.com/.../03MAIR---Algoritmos-de-Optimizacion---2019/tree/master/SEMINARIO<br>
Problema:
> 1. Sesiones de doblaje <br>

Descripción del problema:<br>

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible

(*) La respuesta es obligatoria





                                        

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.




Respuesta

Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


Respuesta

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

Respuesta

Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta

Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Respuesta

(*)Calcula la complejidad del algoritmo

Respuesta

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

Aplica el algoritmo al juego de datos generado

Respuesta

Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Respuesta

In [ ]:
# Liberias
import random
import math
import numpy as np
import pandas as pd
import os


In [ ]:
# Importacion de datos
csv_path = os.path.join('Dataset', 'problema_doblaje.csv')
# Se carga el archivo en un DataFrame
dubbing_data = pd.read_csv(csv_path, header=None, sep=',')

np_takes = dubbing_data.to_numpy()


In [ ]:
def lower_temp(temperature, cool_factor):
    return temperature*cool_factor


def build_index_table(size, name):
    list_index = ["Takes"]
    for i in range(size):
        list_index.append(f"{name}{i+1}")
    return list_index


def keep_temperature(p, n):
    return len(p)*n


def cost(takes):
    total_cost = 0
    step = 6
    start = 0
    end = step
    days = int(len(takes)/6)
    aux_day_cost = np.zeros(shape=days)
    for i in range(days):
        day_session = takes[start:end, 1:len(takes[0])]
        for actor in range(len(day_session[0])):
            current_value = 1 if day_session[:, actor].sum() > 0 else 0
            aux_day_cost[i] += current_value
            total_cost += current_value

        start += step
        end += step
    return total_cost, aux_day_cost


def generate_random_neighbor(takes):
    """
    Genera un vecino aleatorio cambiando una toma de un día aleatorio.
    """
    new_takes = np.copy(takes)

    # Crear una lista con los índices de las filas
    row_indexs = list(range(new_takes.shape[0]))
    # Mezclar los índices de las filas de forma aleatoria
    np.random.shuffle(row_indexs)

    # Intercambiar las filas utilizando los índices mezclados
    return new_takes[row_indexs, :]


def initial_temperature(cost):
    return cost*0.4


def acceptance_requirements(cost, temperature):
    return random.random() < math.exp(-1*cost / temperature)


def simulated_annealing(session, tf, cool_factor):
    day_cost = np.zeros(shape=5)
    best_session = np.copy(session)
    best_cost, day_cost = cost(best_session)
    t = initial_temperature(best_cost)
    it = 0
    while t >= tf:
        it += 1
        for _ in range(keep_temperature(best_session, 1)):

            neighbor = generate_random_neighbor(best_session)
            new_cost, new_day_cost = cost(neighbor)
            difference_cost = new_cost - best_cost
            if difference_cost < 0 or acceptance_requirements(difference_cost, t):
                best_session = np.copy(neighbor)
                best_cost = new_cost
                day_cost = new_day_cost
        t = lower_temp(t, cool_factor)

    return best_session, best_cost, it, day_cost


In [ ]:
solution = simulated_annealing(np_takes, .00001, .85)
df_solution = pd.DataFrame(data=solution[0], columns=build_index_table(10, "Actor ")).set_index('Takes')
days=int(len(np_takes)/6)
step = 6
start = 0
end = step
print(f"Se realizaron 6 tomas por día. Días totales: {days}")
print(f"\nCosto total de las {int(len(np_takes))} tomas: {solution[1]} ")
print(f"Número de iteraciones: {solution[2]}")
print(f"Tomas por día:")


for i in range(days):
    print(f"\nDía: {i+1} costo: {solution[3][i]}")
    display(df_solution.iloc[start:end, :])
    start += step
    end += step

In [240]:
def brute_force(takes):
    new_takes = np.copy(takes)
    total=0
    aux_index=0
    for index, take in enumerate(takes):
        row_indexs = list(range(new_takes.shape[0]))
        for i in range(index,len(takes)-1):
            print(i)
            aux_index=i+1
            aux_val=row_indexs[index]
            row_indexs[index]=row_indexs[aux_index]
            row_indexs[aux_index]=aux_val
            new_takes =  new_takes[row_indexs, :]

            new_cost, new_day_cost = cost(new_takes)
        

            print(new_cost)
            print(new_day_cost)
            
        
        
brute_force(np_takes)

0
38
[7. 8. 8. 7. 8.]
1
38
[7. 8. 8. 7. 8.]
2
38
[7. 8. 8. 7. 8.]
3
38
[7. 8. 8. 7. 8.]
4
38
[7. 8. 8. 7. 8.]
5
38
[7. 8. 8. 7. 8.]
6
38
[7. 8. 8. 7. 8.]
7
39
[7. 9. 8. 7. 8.]
8
38
[7. 8. 8. 7. 8.]
9
39
[8. 8. 8. 7. 8.]
10
38
[8. 7. 8. 7. 8.]
11
38
[8. 7. 8. 7. 8.]
12
38
[8. 7. 8. 7. 8.]
13
39
[9. 7. 8. 7. 8.]
14
39
[9. 7. 8. 7. 8.]
15
39
[8. 8. 8. 7. 8.]
16
38
[8. 8. 7. 7. 8.]
17
37
[7. 8. 7. 7. 8.]
18
38
[8. 8. 7. 7. 8.]
19
38
[7. 9. 7. 7. 8.]
20
39
[7. 9. 7. 8. 8.]
21
39
[7. 8. 8. 8. 8.]
22
38
[7. 8. 8. 7. 8.]
23
37
[8. 7. 8. 7. 7.]
24
38
[9. 8. 8. 7. 6.]
25
38
[8. 7. 9. 7. 7.]
26
39
[8. 7. 9. 7. 8.]
27
38
[8. 7. 8. 8. 7.]
28
38
[8. 7. 8. 8. 7.]
1
38
[8. 7. 8. 8. 7.]
2
38
[8. 7. 8. 8. 7.]
3
38
[8. 7. 8. 8. 7.]
4
38
[8. 7. 8. 8. 7.]
5
38
[8. 7. 8. 8. 7.]
6
38
[8. 7. 8. 8. 7.]
7
37
[8. 6. 8. 8. 7.]
8
36
[7. 6. 8. 8. 7.]
9
38
[7. 8. 8. 8. 7.]
10
38
[7. 8. 8. 8. 7.]
11
38
[7. 8. 8. 8. 7.]
12
37
[6. 8. 8. 8. 7.]
13
37
[6. 9. 7. 8. 7.]
14
36
[7. 8. 6. 8. 7.]
15
37
[7. 7. 8. 8. 7.]
16
38
[