<a href="https://colab.research.google.com/github/geharpz/algoritmos_optimizacion_miar2023/blob/seminario/src/seminario/Seminario_Algoritmos_Diocles_German_Avendano_Ponce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: Diocles Germán Avendaño Ponce <br>
Url: https://github.com/geharpz/algoritmos_optimizacion_miar2023/tree/main/src/seminario/Seminario_Algoritmos_Diocles_German_Avendano_Ponce.ipynb<br>
Problema:
><b>1. Sesiones de doblaje</b> <br>

Descripción del problema:<br>

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible

(*) La respuesta es obligatoria





                                        

### <b>Posibilidades del problema</b>
***1.1 ¿Cuantas posibilidades hay sin tener en cuenta las restricciones?(*)***

***1.2 ¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones***




<b>Respuesta</b>

Para responder ambas preguntas se analizó el trabajo de <b>[1]</b>, por lo que se consideró lo siguiente: 

1. Dada la pregunta y de acorde al problema de coordinación de doblaje, podemos hacer las 30 tomas en un día, siempre y cuando cada toma no dure más de 48 minutos, con respecto a los actores pueden aparecer en cualquier toma, entonces tenemos 30 toma por 10 actores los cuales pueden o no aparecer en las tomas eso nos deja 2 posibilidades. Por tanto $30 \times 10 = 300$ y dos posibles valores con respecto a los actores de $(0, 1)$ <br> 

    Para responder a la pregunta "<b>¿Cuántas posibilidades hay sin tener en cuenta las restricciones? </b>", podemos calcular las posibilidades óseas $x$ usando una permutación sin repetición donde el orden importa, para el producto entre las tomas y los actores, con 2 posibles valores por lo que tenemos la siguiente fórmula: 
    $$x = 2^{(n*m)!}$$ 

    Donde:<br> 
    $n = 30$ -> representa el número de tomas<br> 
    $m = 10$ -> representa el número de actores<br> 
    $2 -> posibles valores (0,1)$<br><br> 
    Reemplazando tenemos:<br> 
    $x = 2^{(30*10!)} $<br> 
    $x = 2^{(300!)} $<br> 
    $x = ?$ ->En este caso realizando la operación en la calculadora nos arroja un error porque el número es demasiado grande para poder realizar el cálculo.<br>

Podemos hacer otras combinaciones, como hacer 5, 6, 10, 20, etc. Tomas por día, pero sería agregarle restricciones, lo cual veremos en el apartado siguiente. 

2. Dada las restricciones del problema de coordinación de doblaje, de las 30 tomas, se puede realizar máximo 6 tomas por día y los actores deben coincidir en las tomas en que sus personajes aparecen, se decidió hacer dicho máximo de tomas permitido por día, osea 6 tomas durante 5 días, para minimizar el costo debemos encontrar el orden idóneo en el cual hacer las tomas. <br> 

    Para responder a la pregunta "<b>¿Cuántas posibilidades hay teniendo en cuenta todas las restricciones? </b>", podemos calcular las posibilidades osea $x$ usando una permutación sin repetición donde el orden importa, para calcular las permutaciones del total de tomas, de estas debemos calcular cuántas permutaciones de 6 elementos se pueden realizar, ósea debemos dividir 30! por 6!  pero de estas 6! permutaciones debemos ordenarlos en conjuntos de 5 elementos distintos, pero no queremos permutaciones repetidas, para eliminarlas procedemos a elevar a la 5 el 6!, por lo que tenemos la siguiente fórmula: $$x = \frac{n!}{m!^k}$$ 

    Donde:<br> 
    $n = 30$ -> Representa el número de tomas<br> 
    $m = 6$ -> Representa el número máximo de tomas por días<br> 
    $k = \frac{n}{m} = \frac{30}{6} = 5  $ -> Representa el número de días necesarios para realizar las 30 tomas si se hacen 6 tomas por día<br><br> 
    Reemplazando tenemos:<br> 
    $x = \frac{30!}{6!^5}$<br> 
    $x = 1370874168\times{10}^{18}$<br> 

Por lo tanto, la respuesta es $1370874168\times{10}^{18}$ posibilidades con las restricciones del problema de coordinación de doblaje 

### <b>2 Modelo para el espacio de soluciones</b>
<b><i>2.1 ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)(*)</i></b>


<b>Respuesta</b>

- Para el problema de coordinación de doblaje se decidió usar un array NumPy, dado a que los valores eran binarios (Enteros ya que se agregó como columna 0 el número de las tomas  al array) y al buen rendimiento que caracteriza a esta librería, los datos son cargados de un CSV el cual contiene 30 filas y 11 columnas, la columna 0 representan el número de cada tomas y las columna del 1 al 10 representan los actores, posteriormente es convertido en un array NumPy.
- Para mostrar los datos de forma tabulada y con una visualización más clara y entendible, se convierte en un DataFrame de Pandas el array NumPy, donde como ya se mencionó anteriormente las filas vienen a representar las tomas y las columnas los actores, los cuales se identifican fácilmente en el DataFrame.

### <b>3 Según el modelo para el espacio de soluciones<b>
***3.1 ¿Cual es la función objetivo?***

<b><i>3.2 ¿Es un problema de maximización o minimización?(*)<i></b>

<b>Respuesta</b>

Para responder las anteriores preguntas se analizo el trabajo de <b>[2]</b> además del razonamiento del presente problema, por que se tiene que:<br>
1. Dada la naturaleza del problema de coordinación de doblaje, donde se busca que el gasto por los servicios de los actores sea el menor posible (minimizar), se puede inferir que se trata de un problema de programación lineal.<br>

La <b>función objetivo</b> viene dada por<br>
$$x = \displaystyle\sum_{i=1}^n a_{i}\times c $$
Donde:<br>
- $x =$ Es el valor incógnito del gasto menor posible por los servicios de los actores<br>
- $t= 30 s$-> Es la cantidad total de tomas<br>
- $m = 6 $-> Es la cantidad maxima de tomas por día<br>
- $n = \frac{t}{m} = \frac{30}{6} = 5$ -> el cual es el número de días considerando 6 tomas por día<br>
- $a =$ representa el número de actores por día<br>
- $c = 1$ -> Es una constante el cual representa el valor que cobran los actores por día
- $i =$ Representa el día actual

2. En cuanto a la pregunta "<b>¿Es un problema de maximización o minimización?</b>", esto se responde con lo anterior expuesto, el problema es de minimización, ya que se busca que los gastos por servicios prestado de los actores en la tomas sea el menor posible.

### <b>4 Diseña un algoritmo para resolver el problema por fuerza bruta</b>

##### <b>Librerías</b>

In [ ]:
# Importar las librerías necesarias
import random  # Para generar números aleatorios si es necesario
import math  # Para operaciones matemáticas avanzadas si son requeridas
import numpy as np  # Para trabajar con arrays y matrices numéricas de manera eficiente
import pandas as pd  # Para leer y manipular datos en formato CSV
import os  # Para interactuar con el sistema operativo y manipular rutas de archivos
import itertools  # Para trabajar con iteraciones y combinaciones
# Definir la ruta del archivo CSV que contiene los datos del problema de doblaje
csv_path = os.path.join('Dataset', 'problema_doblaje.csv')
# Leer los datos del archivo CSV y almacenarlos en un DataFrame de pandas
dubbing_data = pd.read_csv(csv_path, header=None, sep=',')
# Convertir el DataFrame de pandas en una matriz NumPy para facilitar el procesamiento numérico
np_takes = dubbing_data.to_numpy()

##### <b>Funciones generales</b>

In [ ]:
# Función para calcular el coste de los servicios de los actores
def cost(takes):
    # Inicializar variables
    total_cost = 0
    step = 6  # Número de paso 6 por el máximo de tomas por día
    start = 0  # Índice de inicio para cada grupo de tomas
    end = step  # Índice de fin para cada grupo de tomas
    days = int(len(takes) / 6)  # Calcular la cantidad de días necesarios para las tomas
    aux_day_cost = np.zeros(shape=days)  # Array para almacenar los costos por día

    # Iterar a través de los días
    for i in range(days):
        # Obtener las tomas para el día actual
        day_session = takes[start:end, 1:len(takes[0])]
        
        # Calcular el costo para los actores por el día actual
        for actor in range(len(day_session[0])):
            current_value = 1 if day_session[:, actor].sum() > 0 else 0
            aux_day_cost[i] += current_value
            total_cost += current_value

        # Actualizar los índices de inicio y fin para el próximo gripode de tomas por día
        start += step
        end += step

    # Devolver el costo total y el array con los costos por día
    return total_cost, aux_day_cost

# Función build_index_table para agregar los incies
def build_index_table(size, name):
    # Construir una lista con los nombres de las columnas del índice de la tabla
    list_index = ["Takes"]
    for i in range(size):
        list_index.append(f"{name}{i+1}")
    return list_index

<b>Respuesta</b>

#### <b>4.1 Algoritmo de fuerza bruta</b>

In [ ]:
# Se define la función brute_force
def brute_force(takes):
    # Calcula la cantidad de días necesarios para realizar todas las tomas, considerando que hay 6 tomas por día.
    days = int(len(takes) / 6)
    
    # Variable para contar las permutaciones evaluadas.
    count = 1
    
    # Imprime la cantidad total de días necesarios para realizar todas las tomas.
    print(f"Se realizaron 6 tomas por día. Días totales: {days}")
    
    # Itera a través de todas las permutaciones posibles de las tomas.
    for i in itertools.permutations(range(len(takes))):
        # Calcula el costo total y el costo por día para la permutación actual.
        best_cost, day_cost = cost(takes[i, :])
        
        # Imprime el costo total de las tomas para la permutación actual.
        print(f"\nCosto total de las {int(len(takes))} tomas: {best_cost} para la permutación: {count}")
        count += 1
        
        # Crea un DataFrame con la solución de la permutación actual y lo muestra.
        df_solution = pd.DataFrame(data=np_takes[i, :], columns=build_index_table(len(takes[0])-1, "Actor ")).set_index('Takes')
        
        # Variables para imprimir las tomas por día.
        step = 6
        start = 0
        end = step
        
        # Imprime las tomas agrupadas por día.
        print(f"Tomas por día:")
        for j in range(days):
            print(f"\nDía: {j+1} costo: {day_cost[j]}")
            display(df_solution.iloc[start:end, :])  # Muestra las tomas para el día actual.
            start += step
            end += step

In [ ]:
# Se llama a la función brute_force
brute_force(np_takes)

### <b> 5 Calcula la complejidad del algoritmo por fuerza bruta</b>

<b>Respuesta</b>

1. Para calcular la complejidad computacional del algoritmo de fuerza bruta, en la solución propuesta, debemos calcular la complejidad de la funciones que invoca, en este caso invoca a la función "cost" y  "build_index_table"
- Función <b>cost</b>:  En esta función tenemos 2 <b>for</b> anidados  el primero recorre mediante un range la variable <b>days</b> la cual es obtenida al dividir la longitud del array de entrada <b>takes</b> por 6 por lo tanto la complejidad de este primer <b>for</b> es de $O(takes)$ -> $O(n)$ lineal, para el segundo <b>for</b> se recorre la  longitud de la posición [0] del array <b>day_session</b> el cual es obtenido mediante el slice del array de entrada <b>takes</b> por tanto la complejidad es $O(takes)$ -> $O(n)$, y al ser <b>for</b> anidados la complejidad viene dada por:
$O(n) \times O(n)$ -> $O(n^2)$ cuadrática.
- Función <b>build_index_table</b>: En esta función tenemos un <b>for</b> el cual recorre mediante un range la variable de entrada "size" por lo que la complejidad viene dada por $O(size)$ -> $O(n)$ lineal


2. Complejidad del algoritmo de fuerza bruta, en este algoritmo hay 2 <b>for</b> anidados.
- El primer <b>for</b> recorre las permutaciones si repetir de la longitud del array de entrada <b>takes</b> por ende la complejidad es $O(takes!)$ -> $O(n!)$ factorial, dentro de este <b>for</b> se asigna valor a 2 variables <b>best_cost</b> y  <b>day_cost</b> mediante la invocación de la función "cost" el cual recibe como parámetro el array de entrada <b>takes</b>, cuya complejidad viene dada por $O(takes^2)$ -> $O(n^2)$, también se crea un DataFrame mediante el llamado de la función "build_index_table" el cual recibe como parámetro la longitud de índice [0] del array de entrada <b>takes</b> por lo que la complejidad viene dada por $O(takes)$ -> $O(n)$
- El segundo <b>for</b> recorre mediante un range la variable “days” la cual es obtenida al dividir la longitud del array de entrada “takes” por 6 por lo tanto la complejidad de este segundo <b>for</b> es de $O(takes)$ -> $O(n)$ lineal.<br><br>
Calculando la complejidad total tenemos:<br><br>
$O(n!) \times (O(n^2)+O(n)+O(n))$<br>
$O(n!) \times (O(n^2)+2 \cdot O(n))$<br>
$O(n!)$ -> Ya que nos quedamos con la complejidad más grande en este caso obtenemos una complejidad factorial, en el algoritmo de fuerza bruta.

### <b>6 Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta(*)</b>

#### <b>6.1 Algoritmo recocido simulado</b> 

Este algoritmo se escogido al realizar una investigación del trabajo de <b>[2]</b> donde fue implementado dicho algoritmo obteniendo buenos resultados, para entender el algoritmo en profundidad se visualizaron y analizaron los videos de <b>[3]</b>,<b>[4]</b>,<b>[5]</b>,<b>[6]</b>,<b>[7]</b>,<b>[8]</b>,<b>[9]</b>,<b>[10]</b> de los cuales se extrajo el seudocódigo en el que se basa el algoritmo implementado en el presente trabajo, en la figura 1 se visualiza el seudocódigo: 

<img src="img/seudocodigo.png" width="550"><br> 
<font size = 2><b>Figura 1. Seudocódigo del algoritmo de recocido simulado</b></font><br><br> 


#### <b>6.2 ¿Porque mejora el algoritmo de recocido simulado al de fuerza bruta? </b> 

Según lo analizado en el trabajo de <b>[2]</b> y los videos de <b>[3]</b>, <b>[4]</b>, <b>[5]</b>, <b>[6]</b>, <b>[7]</b>, <b>[8]</b>, <b>[9]</b>, <b>[10]</b>: 

1. Eficiencia en problemas complejos. El algoritmo de fuerza bruta prueba todas las soluciones posibles, que puede ser ineficiente y computacionalmente costoso con problemas de un gran espacio de búsqueda, cuyo tamaño para el presente trabajos es de $1370874168\times{10}^{18}$, el cual se obtuvo considerando las restricciones del problema. A diferencia, el algoritmo de recocido simulado es capaz de escapar de mínimos locales y explorar áreas más amplias del espacio de soluciones, haciéndolo más efectivo en problemas complejos y con múltiples óptimos locales. 
  
2. Evita quedar atrapado en mínimos locales. La naturaleza estocástica del algoritmo de recocido simulado le permite aceptar soluciones subóptimas con una cierta probabilidad, lo que le permite escapar de mínimos locales y encontrar soluciones óptimas en el espacio de búsqueda. En cambio, el algoritmo de fuerza bruta puede quedar atrapado en mínimos locales y no llegar a la solución global óptima. 

3. Escalabilidad. A medida que aumenta la complejidad del problema y el espacio de búsqueda, el algoritmo de fuerza bruta se vuelve rápidamente inviable debido al gran número de soluciones a evaluar. Por otro lado, el algoritmo de recocido simulado puede ser más escalable, ya que no requiere evaluar todas las soluciones posibles y puede enfocarse en áreas prometedoras del espacio de búsqueda. 

4. Aceptación de soluciones peores. El algoritmo de recocido simulado acepta soluciones peores con cierta probabilidad, lo que permite explorar más el espacio de búsqueda y encontrar soluciones óptimas en situaciones en las que el algoritmo de fuerza bruta quedaría atascado en soluciones locales subóptimas. 


En el caso del algoritmo por fuerza bruta implementado en el presente problema, la ejecución del algoritmo no se terminó de ejecutar en las pruebas que se realizaron, en cambio el algoritmo de recocido simulado para el tamaño de entrada de 30 tomas y 10 actores toma un tiempo de alrededor de 0.4 a 0.7 segundos, o clara diferencia, este algoritmo nos dará una solución diferente cada vez que se ejecute dada a su naturaleza heurística . 
Cabe mencionar que no existe un algoritmo que sea siempre mejor para todos los problemas. El enfoque del recocido simulado es más adecuado para problemas de optimización, especialmente aquellos con espacios de búsqueda complejos y multidimensionales, mientras que el algoritmo de fuerza bruta puede ser suficiente y más fácil de implementar en problemas más simples y con espacios de búsqueda pequeños. La elección del algoritmo depende de la naturaleza y la complejidad del problema en cuestión. 


<b>Respuesta</b>

#### <b>6.2 Definición del algoritmo recocido simulado</b>

In [ ]:
# Función para reducir la temperatura actual mediante un factor de enfriamiento.
def lower_temp(temperature, cool_factor):
    return temperature * cool_factor

# Función para calcular cuánto tiempo mantener la temperatura actual.
def keep_temperature(p, n):
    return len(p) * n

# Función para generar un vecino aleatorio basado en una permutación de las tomas.
def generate_random_neighbor(takes):
    # Copiar la matriz de tomas para no modificar la original.
    new_takes = np.copy(takes)
    # Generar un índice aleatorio para las filas (tomas).
    row_indexs = list(range(new_takes.shape[0]))
    np.random.shuffle(row_indexs)
    # Reorganizar las filas de la matriz para obtener el vecino aleatorio.
    return new_takes[row_indexs, :]

# Función para determinar la temperatura inicial basada en el costo.
def initial_temperature(cost):
    return cost * 0.4 # 0.4 es un valor asignado dado la investigación 

# Función para comprobar si se acepta una nueva solución en función de su costo y la temperatura actual.
def acceptance_requirements(cost, temperature):
    return random.random() < math.exp(-1 * cost / temperature)

# Función que implementa el algoritmo de recocido simulado.
def simulated_annealing(takes, tf, cool_factor):
    # Inicializar un array para almacenar los costos por día.
    day_cost = np.zeros(shape=5)
    # Copiar las tomas actuales como la mejor solución.
    best_takes = np.copy(takes)
    # Calcular el costo inicial y los costos por día para la mejor solución.
    best_cost, day_cost = cost(best_takes)
    # Calcular la temperatura inicial basada en el costo inicial.
    t = initial_temperature(best_cost)
    # Inicializar una variable para contar las iteraciones realizadas.
    it = 0
    # Bucle principal del algoritmo mientras la temperatura sea mayor o igual a la temperatura final.
    while t >= tf:
        it += 1
        # Realizar una cantidad de iteraciones determinada por la función keep_temperature.
        for _ in range(keep_temperature(best_takes, 1)):
            # Generar un vecino aleatorio y evaluar su costo.
            neighbor = generate_random_neighbor(best_takes)
            new_cost, new_day_cost = cost(neighbor)
            # Calcular la diferencia de costos entre la solución actual y el vecino generado.
            difference_cost = new_cost - best_cost

            # Si el vecino es mejor o cumple con los requisitos de aceptación, actualizar la mejor solución.
            if difference_cost < 0 or acceptance_requirements(difference_cost, t):
                best_takes = np.copy(neighbor)
                best_cost = new_cost
                day_cost = new_day_cost

        # Reducir la temperatura para la siguiente iteración.
        t = lower_temp(t, cool_factor)

    # Devolver la mejor solución encontrada, su costo, el número de iteraciones realizadas y los costos por día.
    return best_takes, best_cost, it, day_cost

In [98]:
# Resolución del problema mediante el algoritmo de recocido simulado.
# Se utiliza el arreglo 'np_takes' como entrada, con una temperatura final de 0.00001 y un factor de enfriamiento de 0.85.
solution = simulated_annealing(np_takes, .00001, .85)

# Se Crea un DataFrame con la solución obtenida, utilizando la función build_index_table para obtener los nombres de las columnas.
# El DataFrame tendrá 30 filas (una para cada toma) y 10 columnas con nombres "Actor 1", "Actor 2", ..., "Actor 10".
# Se establece el índice del DataFrame como la columna "Takes" (números del 1 al 30).
df_solution = pd.DataFrame(data=solution[0], columns=build_index_table(len(np_takes[0])-1, "Actor ")).set_index('Takes')

# Calcular la cantidad total de días requeridos para realizar todas las tomas, considerando que hay 6 tomas por día.
days = int(len(np_takes) / 6)

# Variables para imprimir las tomas por día.
step = 6
start = 0
end = step

# Imprimir información general sobre la solución encontrada.
print(f"Se realizaron 6 tomas por día. Días totales: {days}")
print(f"\nCosto total de las {int(len(np_takes))} tomas: {solution[1]} ")
print(f"Número de iteraciones: {solution[2]}")
print(f"Tomas por día:")

# Iterar a través de los días y mostrar las tomas para cada día en el DataFrame.
for i in range(days):
    print(f"\nDía: {i+1} costo: {solution[3][i]}")
    display(df_solution.iloc[start:end, :])  # Muestra las tomas para el día actual.
    start += step
    end += step

# Imprimir una visualización completa del DataFrame con la solución.
print(f"\n\nVisualización del DataFrame completo con la solución:")
df_solution.style

Se realizaron 6 tomas por día. Días totales: 5

Costo total de las 30 tomas: 32 
Número de iteraciones: 88
Tomas por día:

Día: 1 costo: 8.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
11           1        1        1        0        1        0        0        1   
23           1        0        1        0        0        0        0        0   
3            0        1        0        0        1        0        1        0   
15           1        1        0        0        0        0        1        0   
22           1        1        1        1        0        0        0        0   
12           1        1        1        1        0        1        0        0   

       Actor 9  Actor 10  
Takes                     
11           0         0  
23           0         0  
3            0         0  
15           0         0  
22           0         0  
12           0         0


Día: 2 costo: 5.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
13           1        0        0        1        1        0        0        0   
2            0        0        1        1        1        0        0        0   
17           1        0        1        0        0        0        0        0   
1            1        1        1        1        1        0        0        0   
19           1        0        1        0        0        0        0        0   
7            1        1        0        1        1        0        0        0   

       Actor 9  Actor 10  
Takes                     
13           0         0  
2            0         0  
17           0         0  
1            0         0  
19           0         0  
7            0         0


Día: 3 costo: 6.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
28           1        0        0        1        0        0        0        0   
25           1        1        0        1        0        0        0        0   
5            0        1        0        1        0        0        0        1   
4            1        1        0        0        0        0        1        1   
16           0        0        0        1        0        0        0        0   
9            1        1        0        1        0        0        0        0   

       Actor 9  Actor 10  
Takes                     
28           0         0  
25           0         1  
5            0         0  
4            0         0  
16           0         1  
9            0         0


Día: 4 costo: 6.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
8            1        1        0        0        0        1        0        0   
18           0        0        1        0        0        1        0        0   
26           1        0        1        0        1        0        0        0   
10           1        1        0        0        0        1        0        0   
24           0        0        1        0        0        1        0        0   
29           1        0        0        0        1        1        0        0   

       Actor 9  Actor 10  
Takes                     
8            0         0  
18           0         0  
26           1         0  
10           1         0  
24           0         0  
29           0         0


Día: 5 costo: 7.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
21           0        0        0        0        0        1        0        1   
6            1        1        0        1        1        0        0        0   
27           0        0        0        1        1        0        0        0   
14           1        0        1        0        0        1        0        0   
30           1        0        0        1        0        0        0        0   
20           1        0        1        1        1        0        0        0   

       Actor 9  Actor 10  
Takes                     
21           0         0  
6            0         0  
27           0         0  
14           0         0  
30           0         0  
20           0         0



Visualización del DataFrame completo con la solución:


<b>6.2.1 Que podemos inferir del resultado al ejecutar el algoritmo de recocido simulado</b> 

En las pruebas que se realizaron se obtuvieron un costo de entre 32 y 34 por los servicios de los actores en los 5 días, si consideramos que los 10 actores pueden actuar durante los 5 días, nos daría un costo de 50, con esto comprobamos que el algoritmo si minimiza el costo total de los servicios, tal vez no sea la solución más optima, pero sin duda es una buena minimización, con un bajo tiempo de cálculo para el conjunto de datos del problema.

### <b>7 Calcula la complejidad del algoritmo(*)</b>

<b>Respuesta</b>

1. Para calcular la complejidad del algoritmo recocido simulado implementado como la función “simulated_annealing” debemos calcular la complejidad de las demás funciones que llama, estas son:
- lower_temps
- keep_temperature
- generate_random_neighbor
- initial_temperature
- acceptance_requirements
- cost

La complejidad de la función “cost” ya la calculamos -> $O(n^2)$, las demás funciones que se invocan realizan operaciones internamente relacionados con el array de las tomas el cual es entrada de la función “simulated_annealing”, por ejemplo, la función “lower_temp” recibe como parámetro a <b>temperature</b> y <b>cool_factor</b>, el parámetro <b>temperature</b> es obtenido mediante el resultado de la función “initial_temperature”, la cual recibe como parámetro un valor que es obtenido al calcular el costo del array de las tomas, casos similares con las demás funciones invocadas dentro de “simulated_annealing”, pero ya que ninguna utiliza un bucle interno que dependan de la variable de entrada de la función “simulated_annealing” consideraremos que la complejidad de cada una de ellas es $O(1)$ constante.

2. Dado lo anterior la complejidad del algoritmo de recocido simulado "simulated_annealing" - Dentro de esta tenemos la inicialización de 4 variables, de estas las variables <b>best_cost</b> y <b>day_cost</b> se lo realiza mediante el llamado de la función “cost” la cual recibe como parámetro <b>best_takes</b> el cual obtiene por el array de entrada <b>takes</b>, por lo que diremos que estas asignaciones tienen la complejidad $O(best_takes^2)$ ->$O(n^2)$ cuadrática, esto ya se calculó cuando se obtuvo la complejidad del algoritmo por fuerza bruta 

- Prosiguiendo con el cálculo de complejidad de la función “simulated_annealing” encontramos 2 bucles:  
    - El primero es un <b>while</b> que se ejecutará cuando la variable <b>t</b> (la cual es obtenida mediante la función “initial_temperature” que su vez recibe un parámetro que representa el costo del array de entrada <b>takes</b>) sea menor o igual que al parámetro de entrada <b>tf</b> por lo cual se considera este primer bucle tiene una complejidad de $O(t)$ ->  $O(n)$ lineal 
    - Para el segundo bucle que se encuentra dentro del primero , tenemos un <b>for</b> el cual se ejecuta mediante de un range que usa como parámetro el resultado de la función “keep_temperature” que a su vez recibe como parámetro a <b> best_takes </b> la cual es obtenida mediante el array de entrada <b>takes</b>, entonces la complejidad de este buche es $O(takes)$ ->$O(n)$ lineal, dentro de este bucle tenemos  la asignación de 2 variables locales <b>new_cost</b> y <b>new_day_cost</b> mediante el llamado de la función “cost”, esta asignación tiene una complejidad de $O(n^2)$ cuadrática. 


Calculando la complejidad total tenemos:<br> 

$O(n^2) + (O(n) \times O(n) \times  O(n^2))$ <br> 
$O(n^2) + (O(n^2)  \times  O(n^2))$ <br> 
$O(n^2) + O(n^4)$ <br> 
$ O(n^4)$ -> Ya que nos quedamos con la complejidad más grande, en este caso polinomial, para el algoritmo de recocido simulado es $n$ elevada a la cuarta 





### <b>8 Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios</b>

<b>Respuesta</b>

In [135]:
# Se Genera una matriz 30x10 con valores aleatorios (0 o 1) usando randint de numpy.
# Esto crea un array llamado np_random que contiene 30 filas y 10 columnas.
# Cada valor es un número aleatorio entre 0 y 1 (inclusive).
np_random = np.random.randint(2, size=(30, 10))

# Crear un array con números enteros desde 1 hasta 30 (inclusive) usando arange de numpy.
# Luego, darle forma de 1 fila y 30 columnas para obtener np_index.
np_index =  np.arange(1, 31, 1, dtype=int).reshape(1, 30)

# Insertar el array np_index como primera columna en el array np_random.
# El parámetro axis=1 indica que se debe insertar como columna (a lo largo de las columnas).
# Esto crea una matriz que tiene en la primera columna los números del 1 al 30 y en las demás columnas los valores aleatorios.
np_random = np.insert(np_random, 0, np_index, axis=1)

# Imprimir un mensaje y mostrar la matriz np_random con los datos generados aleatoriamente.
print("Los datos generados aleatoriamente son:")
print(np_random)

Los datos generados aleatoriamente son:
[[ 1  0  0  0  0  1  0  0  0  0  1]
 [ 2  1  1  1  0  1  0  0  0  1  1]
 [ 3  0  1  0  0  1  0  0  1  1  0]
 [ 4  1  1  1  1  1  0  1  1  1  1]
 [ 5  0  1  0  0  1  1  0  0  0  1]
 [ 6  1  0  1  0  0  0  1  1  0  1]
 [ 7  0  1  1  0  0  1  1  0  1  1]
 [ 8  0  0  1  0  0  1  0  0  0  1]
 [ 9  0  1  0  1  1  0  0  1  1  1]
 [10  0  1  0  1  1  1  1  1  0  0]
 [11  1  1  1  1  1  0  1  0  0  0]
 [12  0  1  1  0  1  1  0  1  0  1]
 [13  1  0  1  0  0  0  1  0  0  0]
 [14  0  1  0  1  0  0  1  1  0  0]
 [15  0  0  1  1  1  1  0  0  0  1]
 [16  1  0  0  0  1  0  0  1  0  1]
 [17  0  0  1  1  1  0  1  1  0  0]
 [18  1  1  1  1  1  1  1  0  1  1]
 [19  0  1  1  1  1  0  0  0  1  1]
 [20  1  1  1  0  1  0  1  1  0  0]
 [21  1  0  0  0  0  1  0  0  0  1]
 [22  0  0  0  1  0  0  0  1  1  1]
 [23  1  1  1  0  0  0  0  1  0  0]
 [24  0  1  1  0  1  1  1  1  0  1]
 [25  0  0  0  1  1  0  1  0  0  1]
 [26  0  0  1  1  0  0  1  0  1  1]
 [27  0  1  0  0  1  0  

### <b>9 Aplica el algoritmo al juego de datos generado</b>

<b>Respuesta</b>

In [141]:
# Se utiliza el array 'np_random' (30 filas y 11 columnas) como entrada, con una temperatura final de 0.00001 y un factor de enfriamiento de 0.85.
solution = simulated_annealing(np_random, .00001, .85)

# Se Crea un DataFrame con la solución obtenida, utilizando la función build_index_table para obtener los nombres de las columnas.
# El DataFrame tendrá 30 filas (una para cada toma) y 10 columnas con nombres "Actor 1", "Actor 2", ..., "Actor 10".
# Se establece el índice del DataFrame como la columna "Takes" (números del 1 al 30).
df_solution = pd.DataFrame(data=solution[0], columns=build_index_table(10, "Actor ")).set_index('Takes')

# Calcular la cantidad total de días requeridos para realizar todas las tomas, considerando que hay 6 tomas por día.
days = int(len(np_takes) / 6)

# Variables para imprimir las tomas por día.
step = 6
start = 0
end = step

# Imprimir información general sobre la solución encontrada.
print(f"Se realizaron 6 tomas por día. Días totales: {days}")
print(f"\nCosto total de las {int(len(np_random))} tomas: {solution[1]} ")
print(f"Número de iteraciones: {solution[2]}")
print(f"Tomas por día:")

# Iterar a través de los días y mostrar las tomas para cada día en el DataFrame.
for i in range(days):
    print(f"\nDía: {i+1} costo: {solution[3][i]}")
    display(df_solution.iloc[start:end, :])  # Muestra las tomas para el día actual.
    start += step
    end += step

# Imprimir una visualización completa del DataFrame con la solución de los datos aleatorios generados.
print(f"\n\nVisualización del DataFrame completo con la solución de los datos aleatorios son:")
df_solution.style


Se realizaron 6 tomas por día. Días totales: 5

Costo total de las 30 tomas: 44 
Número de iteraciones: 90
Tomas por día:

Día: 1 costo: 9.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
4            1        1        1        1        1        0        1        1   
2            1        1        1        0        1        0        0        0   
29           1        1        0        0        1        0        1        0   
11           1        1        1        1        1        0        1        0   
3            0        1        0        0        1        0        0        1   
16           1        0        0        0        1        0        0        1   

       Actor 9  Actor 10  
Takes                     
4            1         1  
2            1         1  
29           1         0  
11           0         0  
3            1         0  
16           0         1


Día: 2 costo: 9.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
30           0        1        0        0        0        0        1        1   
25           0        0        0        1        1        0        1        0   
22           0        0        0        1        0        0        0        1   
9            0        1        0        1        1        0        0        1   
15           0        0        1        1        1        1        0        0   
7            0        1        1        0        0        1        1        0   

       Actor 9  Actor 10  
Takes                     
30           0         0  
25           0         1  
22           1         1  
9            1         1  
15           0         1  
7            1         1


Día: 3 costo: 9.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
14           0        1        0        1        0        0        1        1   
10           0        1        0        1        1        1        1        1   
8            0        0        1        0        0        1        0        0   
17           0        0        1        1        1        0        1        1   
27           0        1        0        0        1        0        0        1   
28           0        0        1        1        0        1        1        1   

       Actor 9  Actor 10  
Takes                     
14           0         0  
10           0         0  
8            0         1  
17           0         0  
27           1         0  
28           0         1


Día: 4 costo: 9.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
26           0        0        1        1        0        0        1        0   
5            0        1        0        0        1        1        0        0   
18           1        1        1        1        1        1        1        0   
21           1        0        0        0        0        1        0        0   
13           1        0        1        0        0        0        1        0   
19           0        1        1        1        1        0        0        0   

       Actor 9  Actor 10  
Takes                     
26           1         1  
5            0         1  
18           1         1  
21           0         1  
13           0         0  
19           1         1


Día: 5 costo: 8.0


Actor 1  Actor 2  Actor 3  Actor 4  Actor 5  Actor 6  Actor 7  Actor 8  \
Takes                                                                           
23           1        1        1        0        0        0        0        1   
1            0        0        0        0        1        0        0        0   
6            1        0        1        0        0        0        1        1   
24           0        1        1        0        1        1        1        1   
20           1        1        1        0        1        0        1        1   
12           0        1        1        0        1        1        0        1   

       Actor 9  Actor 10  
Takes                     
23           0         0  
1            0         1  
6            0         1  
24           0         1  
20           0         0  
12           0         1



Visualización del DataFrame completo con la solución de los datos aleatorios son:


<b>9.1 Que podemos inferir del resultado al ejecutar el algoritmo de recocido simulado con el juego de datos aleatorio</b>  

En las pruebas que se realizaron se obtuvieron un costo de entre 43 y 45 por los servicios de los actores en los 5 días, depende de como esten los valores de dicho conjunto de datos, como el caso con los datos originales del problema, podemos observar que el algoritmo minimiza el costo de 50 por los servicios (Si consideramos que todos actores realicen al menos una toma por día).

### <b>10 Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo</b>

<b>Respuesta</b>

<b>Bibliografía</b>

 <b>[1]</b> E. Schaeffer, “Complejidad computacional de problemas y el análisis y diseño de algoritmos,” Publicación en lı́nea, vol. 34, 2011.<br> 

 

<b>[2] </b>A. C. Lima and M. L. C. Rodrı́guez, “Máster en técnicas estadı́sticas”.<br> 

<b>[3] </b>José Manuel Galán. Recocido simulado (1 de 8). Introducción. (24 de marzo de 2020). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=0doM37ZEY4g<br> 

<b>[4] </b>José Manuel Galán. Recocido simulado (2 de 8). Recocido. (24 de marzo de 2020). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=fhyJ4f4SDY4<br> 

<b>[5] </b>José Manuel Galán. Recocido simulado (3 de 8). Recocido Simulado. (24 de marzo de 2020). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=MDp6L-8FnjE<br> 

<b>[6] </b>José Manuel Galán. Recocido simulado (4 de 8). Algoritmo Básico I. (24 de marzo de 2020). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=oGxVyzPjAOY<br> 

<b>[7] </b>José Manuel Galán. Recocido simulado (5 de 8). Algoritmo Básico II. (24 de marzo de 2020). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=Xe63l4kpuMg<br> 

<b>[8] </b>José Manuel Galán. Recocido simulado (6 de 8). Implementación. (24 de marzo de 2020). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=5Wf66z1I22k<br>  

<b>[9] </b>José Manuel Galán. Recocido simulado (7 de 8). Ejemplo. (24 de marzo de 2020). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=7VElS4CFtxs<br>  

<b>[10] </b>José Manuel Galán. Recocido simulado (8 de 8). Resumen. (16 de octubre de 2019). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=fpvS-QJbD4U<br> 

<b>[11]</b> Chio Code. Notación Big O | Análisis de algoritmos de forma sencilla. (9 de diciembre de 2020). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=MyAiCtuhiqQ<br> 

<b>[12]</b> Udearroba. Informática I: U7 - Complejidad constante, logarítmica y lineal. (26 de agosto de 2019). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=vvnSJWhUjDs<br> 

<b>[13]</b> Udearroba. Informática I: U7 - Complejidad log-lineal polinómica y exponencial. (26 de agosto de 2019). Accedido el 27 de julio de 2023. [Video en línea]. Disponible: https://www.youtube.com/watch?v=e8MPK8hMSo4 




### <b>11 Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño</b>

<b>Respuesta</b>

Para este problema de coordinación de actores de doblaje, dado a lo inferido al realizar análisis del trabajo de <b>[2]</b> y al conocimiento adquirido al desarrollar el presente trabajo, se pueden añadir otras restricciones y variaciones, realizar una investigación sobre diferentes algoritmos. 

- Algoritmos de optimización que puedan abordar problemas similares, como la programación lineal, la programación entera, algoritmos genéticos u otras técnicas heurísticas. 
- Desarrollo de soluciones, implementar los algoritmos seleccionados y adaptarlos al modelo matemático específico del problema. Probar las soluciones en ejemplos pequeños para validar su eficacia. 
- Exploración de variantes y ajustes. Se puede considerar posibles variantes del problema o aspectos adicionales a tener en cuenta, como minimizar el tiempo total de grabación o reducir los desplazamientos de los actores. 
- Evaluar las soluciones. Obtenidas en función del costo y otros criterios relevantes. Comparar diferentes enfoques y seleccionar la mejor opción. 
- Optimización y refinamiento. Si es necesario, realizar ajustes en los algoritmos o en el modelo para mejorar la eficiencia y precisión de las soluciones. 
- Validación y robustez. Verificar que las soluciones propuestas cumplan con todas las restricciones y no violen ninguna limitación del problema. 
- Escalabilidad: Considerar cómo el enfoque utilizado se comporta al aumentar el tamaño del problema. Asegurarse de que la solución sea factible y eficiente para problemas de mayor envergadura. 
- Aplicación práctica. Una vez que se ha encontrado una solución adecuada, implementarla en la planificación real de las sesiones de doblaje y evaluar su rendimiento en el contexto del mundo real. 
- Monitoreo y mejora continua. Establecer un proceso de seguimiento y revisión para realizar mejoras continuas en la coordinación del doblaje y reducir los costos en futuras producciones, ya que como se indica en el trabajo de <b>[2]</b> es problema que tienen pequeñas variaciones a través del tiempo, por lo que los algoritmos que se implemente para minimizar el costo deben adaptarse a las nuevas necesidades. 

En conclusión se puede realizar un gran número de modificaciones y adaptaciones en el estudio del problema, los algoritmos heurísticos proporcionan buenas soluciones por lo que son bastante indicados para este tipo de problemas, como ya se mencionó anteriormente no hay una algoritmo que sea siempre el mejor para todos los problema, hay que investigar y modelar uno que se acople mejor a las necesidades de cada uno, habrá problemas que no se puedan modelar exactamente a la realizad podemos agregar restricciones, modificaciones y validar que estas nos lleven a soluciones deseadas. 